---
version: "2"
services:
  nextcloud:
    image: hub-mirror.c.163.com/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${NEXTCLOUD_CONFIG_PATH}:/config
      - ${NEXTCLOUD_DATA_PATH}:/data
    ports:
      - ${PORT}:443
    restart: unless-stopped
    depends_on:
      - nextcloud_db
  nextcloud_db:
    image: hub-mirror.c.163.com/linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${Timezone}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${MARIADB_CONFIG_PATH}:/config
    restart: unless-stopped
    